services:
  app:
    build:
      context: .
      target: development
    ports:
      - "${PORT:-5001}:${PORT:-5001}"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=development
    command: npm run start:dev

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    command: mongod --quiet --logpath /dev/null

volumes:
  mongodb_data:
