version: "3.8"

services:
  app:
    build: .
    ports:
      - "${PORT:-5001}:${PORT:-5001}"
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/dist
    env_file:
      - .env
    depends_on:
      - db
    command: npm run start:dev

  db:
    image: postgres:15-alpine
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_NAME:-perceptron}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
